import React, {ReactElement, useState} from "react";
import Home from '../../../components/searching-components/components/Home/Home';
import { ThemeProvider } from "styled-components";
import Theme from "../../../components/searching-components/models/Theme";
import themes from "../../../components/searching-components/themes";
import HeaderForRest from '../../../components/header-for-rest-section/header-for-rest-section'
import SortInfo from "../../../components/sorting-components/SortInfo/SortInfo";
import {DepthFirstDesc} from "../../../searching-algorithms/dfs";
import Head from "next/head";


const Dfs: React.FC<{}> = (): ReactElement => {
  const [globalTheme, setGlobalTheme] = useState<Theme>(themes.light);

  return (
    <>
    <Head>
    <title>Algolizer | DFS</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/search.svg" />
    </Head>
    <HeaderForRest />
    <ThemeProvider theme={globalTheme}>

      <Home changeTheme={setGlobalTheme}></Home>
    </ThemeProvider>
    <SortInfo {...DepthFirstDesc}></SortInfo>
    </>
  );
};

export default Dfs;
