import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import Header from '../../components/header-section/header-section'
import HeroSection from '../../components/hero-section/hero-section'
import ContentAlgorithmSection from '../../components/content-algorithm-section/content-algorithm-section'
import ContentWhyUsSection from '../../components/content-whyus-section/content-whyus-section'
import ContentAboutUsSection from '../../components/content-aboutus-section/content-aboutus-section'
import ContentHowItWorks from '../../components/content-howitworks-section/content-howitworks-section'
import ByStudentOf from '../../components/content-bystudentof-section/content-bystudentof-section'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Algolizer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/HeroPic.ico" />
      </Head>
      <Header />
      <HeroSection />
      <ContentAlgorithmSection />
      <ContentWhyUsSection />
      <ContentAboutUsSection/>
      <ContentHowItWorks />
      <ByStudentOf />
     </>
  )
}
